version: '2'
services:
  micro2notification-app:
    image: micro2notification
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATA_MONGODB_URI=mongodb://micro2notification-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=Micro2Notification
      - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot before the application
      - SPRING_DATA_JEST_URI=http://micro2notification-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://micro2notification-elasticsearch:9200
  micro2notification-mongodb:
    extends:
      file: mongodb.yml
      service: micro2notification-mongodb
  micro2notification-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: micro2notification-elasticsearch
  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
