version: '2'
services:
  micro2notification-mongodb:
    image: mongo:4.0.9
    ports:
      - '27017:27017'
    command: mongos --configdb micro2notification-mongodb-config
  micro2notification-mongodb-node:
    build:
      context: .
      dockerfile: mongodb/MongoDB.Dockerfile
    command: mongod --replSet rs1 --noprealloc --smallfiles
  micro2notification-mongodb-config:
    image: mongo:4.0.9
    container_name: micro2notification-mongodb-config
    command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
